package:
  name: "dnoise"
  version: "1.4"

build:
  number: 0

source:
  path: ../DnoisE
  #git_url: https://github.com/adriantich/DnoisE.git
  
requirements:
  host:
    - python
    - setuptools
    - pip
  build:
    - python >=3.8
    - nuitka =1.8
    - patchelf
    # following required in build for nuitka to compile
    - pandas =2.0
    - numpy >=1.21
    - tqdm
    - python-levenshtein =0.21
  run:
    - python >=3.8
    - pandas =2.0
    - numpy >=1.21
    - tqdm
    - python-levenshtein =0.21

about:
  home: https://github.com/adriantich/DnoisE
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Denoise sequence data sets from Illumina using distance corrected according to the entropy of each codon position"

test:
  imports:
    - dnoise
  commands:
    - DnoisE.bin -h
    - dnoise -h

extra:
  recipe-maintainers:
    - adriantich

