package:
  name: "dnoise"
  version: "1.2"

source:
  path: ../DnoisE
  #git_url: https://github.com/adriantich/DnoisE.git
  
requirements:
  host:
    - python
    - setuptools
    - pip
  build:
    - python
    - cython
    - nuitka
    - git
  run:
    - python
    - pandas
    - numpy
    - tqdm
    - python-levenshtein
#    - Levenshtein

about:
  home: https://github.com/adriantich/DnoisE
  license: GNU GENERAL PUBLIC LICENSE
  license_familY: GNU
  license_file: LICENSE
  summary: "Denoise sequence data sets from Illumina using distance corrected according to the entropy of each codon position"

extra:
  recipe-maintainers:
    - adriantich

